const ARTISAN_SKILLS = [
  'Plumber',
  'Electrician',
  'Carpenter',
  'Painter',
  'Tiler',
  'Bricklayer',
  'Welder',
  'AC Technician',
  'Generator Repair',
  'Auto Mechanic',
  'Phone / Laptop Repair',
  'Tailor',
  'Barber',
  'Hairdresser',
  'Makeup Artist',
  'Chef / Cook',
  'Cleaner',
  'Laundry',
  'Security Guard',
  'Driver',
  'Photographer',
  'Videographer',
  'Graphic Designer',
  'Web Developer',
  'POP / Ceiling Work',
  'Fumigation',
  'Solar Installation',
  'CCTV / Security Systems',
  'Interior Decorator',
  'Event Planner',
];

module.exports = ARTISAN_SKILLS;
